- name: "restart synapse service"
  systemd:
    name: "container-synapse.service"
    state: restarted
    enabled: true
    daemon_reload: true
- name: "restart synapse admin service"
  systemd:
    name: "container-synapse-admin.service"
    state: restarted
    enabled: true
    daemon_reload: true
- name: "restart matrix dimension service"
  systemd:
    name: "container-matrix-dimension.service"
    state: restarted
    enabled: true
    daemon_reload: true
- name: "restart mautrix whatsapp service"
  systemd:
    name: "container-mautrix-whatsapp.service"
    state: restarted
    enabled: true
    daemon_reload: true
