---
- name: create dir for keycloak provider
  file:
    path: /usr/local/authproviders
    state: directory
- name: download discord provider keycloak
  get_url:
    url: https://github.com/wadahiro/keycloak-discord/releases/download/v0.4.0/keycloak-discord-0.4.0.jar
    dest: /usr/local/authproviders/keycloak-discord-0.4.0.jar
- name: create keycloak container
  containers.podman.podman_container:
    name: keycloak
    image: quay.io/keycloak/keycloak:latest
    network: web
    command: start --auto-build
    volumes: /usr/local/authproviders:/opt/keycloak/providers
    env:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_admin_password }}"
      KC_PROXY: "edge"
      KC_DB: "postgres"
      KC_DB_URL_HOST: "postgres"
      KC_DB_URL_PORT: "5432"
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "{{ postgres_password }}"
      KC_HOSTNAME: "id.dogehub.eu"
    generate_systemd:
      path: /etc/systemd/system/
      wants:
        - container-postgres.service
  notify: "restart keycloak service"

  environment:
    PODMAN_SYSTEMD_UNIT: "container-keycloak.service"
