- hosts: archpi
  roles:
    - base
    - wireguard
    - cloudflare-ddns
  module_defaults:
    containers.podman.podman_container:
      generate_systemd:
        path: /etc/systemd/system/
      state: created
      recreate: "{{ 'yes' if rcr is defined else 'no' }}"
      timezone: "{{ podman_timezone }}"
      ipc: shareable
      labels:
        io.containers.autoupdate: registry
