---
- hosts: archserver
  roles:
    # - { role: server }
    - base
    - pihole
    - caddy
    - lldap
    - mariadb
    - redis
    - authelia
    - nextcloud
    - vaultwarden

  module_defaults:
    containers.podman.podman_container:
      generate_systemd:
        path: /etc/systemd/system/
      state: created
      #recreate: yes
      timezone: "{{ podman_timezone }}"
      ipc: shareable
      labels:
        io.containers.autoupdate: registry
    containers.podman.podman_pod:
      generate_systemd:
        path: /etc/systemd/system/
      state: created
