---
- hosts: archserver
  roles:
    # - { role: server }

    - base
    #- wireguard
    - pihole
    - caddy
    - lldap
    - mariadb
    - redis
    - authelia
    - nextcloud
    - vaultwarden
    - polymcbot

  module_defaults:
    containers.podman.podman_container:
      generate_systemd:
        path: /etc/systemd/system/
      state: created
      recreate: "{{ 'yes' if rcr is defined else 'no' }}"
      timezone: "{{ podman_timezone }}"
      ipc: shareable
      labels:
        io.containers.autoupdate: registry
