---
- name: prepare dir
  file:
    path: /srv/caddy/{{ item }}
    state: directory
  loop:
    - data
    - config
    - config/static
- name: cloudflare ssl
  import_tasks: cloudflare_ssl.yml
- name: copy Caddyfile
  copy:
    src: Caddyfile
    dest: /srv/caddy/Caddyfile
- name: create caddy container
  containers.podman.podman_container:
    name: caddy
    image: "caddy-custom"
    network: web
    volumes:
      - /srv/caddy/data/:/data
      - /srv/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/caddy/config:/config
    publish:
      - "80:80"
      - "443:443"
    env:
      CF_API_TOKEN: "{{ cloudflare_key }}"
    labels:
  notify: "restart caddy service"
