---
- name: create dirs
  file:
    path: "/srv/mx/{{ item }}"
    state: directory
  loop:
    - synapse
    - whatsapp
    - discord
    - facebook
- name: check if config generated
  stat:
    path: /srv/mx/synapse/homeserver.yaml
  register: hs_test
- name: generate config
  containers.podman.podman_container:
    name: config-gen
    image: docker.io/matrixdotorg/synapse:latest
    generate_systemd: {}
    rm: true
    state: started
    command: generate
    volumes: /srv/mx/synapse:/data
    env:
      SYNAPSE_SERVER_NAME: "dogehub.eu"
      SYNAPSE_REPORT_STATS: "no"
  when: not hs_test.stat.exists
- name: create caddy .well-known/matrix/server
  file:
    path: /srv/caddy/config/static/.well-known/matrix
    state: directory
- name: copy .well-known/matrix/server
  copy:
    src: matrix_server.json
    dest: /srv/caddy/config/static/.well-known/matrix/server
- name: copy .well-known/matrix/client
  copy:
    src: matrix_client.json
    dest: /srv/caddy/config/static/.well-known/matrix/client
- name: template homeserver.yaml
  template:
    src: homeserver.yaml.j2
    dest: /srv/mx/synapse/homeserver.yaml
- name: create synapse container
  containers.podman.podman_container:
    name: synapse
    image: docker.io/matrixdotorg/synapse:latest
    network: web
    volumes: /srv/mx/synapse:/data
    generate_systemd:
      new: yes
      path: /etc/systemd/system
      wants:
        - container-postgres.service
  notify: "restart synapse service"
- name: create synapse-admin container
  containers.podman.podman_container:
    name: synapse-admin
    image: docker.io/awesometechnologies/synapse-admin:latest
    network: web
    env:
      REACT_APP_SERVER: "https://mx.dogehub.eu"
  notify: "restart synapse admin service"
- name: check if whatsapp config generated
  stat:
    path: /srv/mx/whatsapp/config.yaml
  register: ws_test
# === CONFIG GENERATOR START ===
- name: copy mautrix-whatsapp config
  copy:
    src: whatsapp.yml
    dest: /srv/mx/whatsapp/config.yaml
  when: not ws_test.stat.exists
- name: postgres creds in whatsapp config
  lineinfile:
    path: /srv/mx/whatsapp/config.yaml
    search_string: "    uri:"
    line: "    uri: postgres://postgres:{{ postgres_password }}@postgres/mautrix-whatsapp?sslmode=disable"
  when: not ws_test.stat.exists
- name: create mautrix-whatsapp generator container
  containers.podman.podman_container:
    name: mautrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp:latest
    network: web
    volumes: /srv/mx/whatsapp:/data
    generate_systemd: {}
    rm: yes
    state: started
  when: not ws_test.stat.exists
- name: wait for container to generate registration
  wait_for:
    path: /srv/mx/whatsapp/registration.yaml
  when: not ws_test.stat.exists
- name: copy registration to synapse
  copy:
    remote_src: yes
    src: /srv/mx/whatsapp/registration.yaml
    dest: /srv/mx/synapse/whatsapp-registration.yaml
# === CONFIG GENERATOR END ===
- name: create mautrix-whatsapp container
  containers.podman.podman_container:
    name: mautrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp:latest
    network: web
    volumes: /srv/mx/whatsapp:/data
    generate_systemd:
      path: /etc/systemd/system
      wants:
        - container-synapse.service
      new: yes
  notify: "restart mautrix whatsapp service"
- name: check if discord config generated
  stat:
    path: /srv/mx/discord/config.yaml
  register: dc_test
# === CONFIG GENERATOR START ===
- name: copy mautrix-discord config
  copy:
    src: discord.yml
    dest: /srv/mx/discord/config.yaml
  when: not dc_test.stat.exists
- name: postgres creds in discord config
  lineinfile:
    path: /srv/mx/discord/config.yaml
    search_string: "    uri:"
    line: "    uri: postgres://postgres:{{ postgres_password }}@postgres/mautrix-discord?sslmode=disable"
  when: not dc_test.stat.exists
- name: create mautrix-discord generator container
  containers.podman.podman_container:
    name: mautrix-discord
    image: dock.mau.dev/mautrix/discord:latest
    network: web
    volumes: /srv/mx/discord:/data
    generate_systemd: {}
    rm: yes
    state: started
  when: not dc_test.stat.exists
- name: wait for container to generate registration
  wait_for:
    path: /srv/mx/discord/registration.yaml
  when: not dc_test.stat.exists
- name: copy registration to synapse
  copy:
    remote_src: yes
    src: /srv/mx/discord/registration.yaml
    dest: /srv/mx/synapse/discord-registration.yaml
# === CONFIG GENERATOR END ===
# DISCORD
- name: create mautrix-discord container
  containers.podman.podman_container:
    name: mautrix-discord
    image: dock.mau.dev/mautrix/discord:latest
    network: web
    volumes: /srv/mx/discord:/data
    generate_systemd:
      path: /etc/systemd/system
      wants:
        - container-synapse.service
      new: yes
  notify: "restart mautrix discord service"
# /DISCORD
# === CONFIG GENERATOR START ===
- name: check if facebook config generated
  stat:
    path: /srv/mx/facebook/config.yaml
  register: fb_test
- name: template mautrix-facebook config
  template:
    src: facebook.yml.j2
    dest: /srv/mx/facebook/config.yaml
  when: not fb_test.stat.exists
- name: create mautrix-facebook generator container
  containers.podman.podman_container:
    name: mautrix-facebook
    image: dock.mau.dev/mautrix/facebook:latest
    network: web
    volumes: /srv/mx/facebook:/data
    generate_systemd: {}
    rm: yes
    state: started
  when: not fb_test.stat.exists
- name: wait for container to generate registration
  wait_for:
    path: /srv/mx/facebook/registration.yaml
  when: not fb_test.stat.exists
- name: copy registration to synapse
  copy:
    remote_src: yes
    src: /srv/mx/facebook/registration.yaml
    dest: /srv/mx/synapse/facebook-registration.yaml
# === CONFIG GENERATOR END ===
# FACEBOOK
- name: create mautrix-facebook container
  containers.podman.podman_container:
    name: mautrix-facebook
    image: dock.mau.dev/mautrix/facebook:latest
    network: web
    volumes: /srv/mx/facebook:/data
    generate_systemd:
      path: /etc/systemd/system
      wants:
        - container-synapse.service
      new: yes
  notify: "restart mautrix facebook service"
# /FACEBOOK
