---
- name: create polymcbot container
  containers.podman.podman_container:
    name: polymcbot
    image: ghcr.io/polymc/bot:latest
    env:
      DISCORD_TOKEN: "{{ polymcbot_key }}"
      DISCORD_APP: "977174139297230888"
  notify: "restart polymcbot service"
