---
- name: "restart pihole service"
  systemd:
    name: "container-pihole.service"
    state: restarted
    enabled: true
    daemon_reload: true
- name: "restart caddy service"
  systemd:
    name: "container-caddy.service"
    state: restarted
    enabled: true
    daemon_reload: true
- name: "restart bitwarden service"
  systemd:
    name: "container-bitwarden.service"
    state: restarted
    enabled: true
    daemon_reload: true
- name: "restart lldap service"
  systemd:
    name: "container-lldap.service"
    state: restarted
    enabled: true
    daemon_reload: true
- name: "restart cloudflare ddns service"
  systemd:
    name: "container-cloudflare-ddns.service"
    state: restarted
    enabled: true
    daemon_reload: true
