---
- name: create dirs
  file:
    path: /srv/synapse
    state: directory
- name: create nextcloud container
  containers.podman.podman_container:
    name: nextcloud
    image: docker.io/library/nextcloud:latest
    network: web
    env:
      MYSQL_HOST: "mariadb"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "{{ mariadb_password }}"
      REDIS_HOST: "redis"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.{{ main_domain }}"
      APACHE_DISABLE_REWRITE_IP: "1"
      TRUSTED_PROXIES: "10.0.0.0/8"
    volumes: /srv/nextcloud:/var/www/html
    generate_systemd:
      path: /etc/systemd/system
      wants:
        - container-mariadb.service
        - container-redis.service
  notify: "restart nextcloud service"
  environment:
    PODMAN_SYSTEMD_UNIT: "container-nextcloud.service"
