---
- name: create dirs
  file:
    path: /srv/nextcloud
    state: directory
- name: create nextcloudcron services
  copy:
    src: "nextcloudcron.{{ item }}"
    dest: "/etc/systemd/system/nextcloudcron.{{ item }}"
  loop:
    - timer
    - service
  notify: "enable nextcloudcron timer"
- name: create nextcloud container
  containers.podman.podman_container:
    name: nextcloud
    image: docker.io/library/nextcloud:latest
    network: web
    env:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "nextcloud"
      REDIS_HOST: "redis"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.dogehub.eu"
      APACHE_DISABLE_REWRITE_IP: "1"
      TRUSTED_PROXIES: "10.0.0.0/8"
    volumes: /srv/nextcloud:/var/www/html
    generate_systemd:
      path: /etc/systemd/system
      wants:
        - container-postgres.service
        - container-redis.service
      new: yes
  notify: "restart nextcloud service"
