---
- name: prepare dir
  file:
    path: /srv/authelia
    state: directory
- name: template authelia config
  template:
    src: authelia-config.yml.j2
    dest: /srv/authelia/configuration.yml
- name: create authelia container
  containers.podman.podman_container:
    name: authelia
    image: docker.io/authelia/authelia:latest
    network: web
    volumes: /srv/authelia:/config
    generate_systemd:
      path: /etc/systemd/system
      wants:
        - container-mariadb.service
        - container-redis.service
  notify: "restart authelia service"
  environment:
    PODMAN_SYSTEMD_UNIT: "container-authelia.service"
