---
- name: create bitwarden container
  containers.podman.podman_container:
    name: bitwarden
    image: docker.io/vaultwarden/server:latest
    network: web
    env:
      SIGNUPS_ALLOWED: "false"
    volumes: /srv/vaultwarden:/data
  notify: "restart bitwarden service"
