---
- name: create dirs
  file:
    state: directory
    path: /srv/lldap
- name: create lldap container
  # ports:
  # 3890 for ldap
  # 17170 for webui
  containers.podman.podman_container:
    name: lldap
    state: created
    image: docker.io/nitnelave/lldap
    network: web
    generate_systemd:
      path: /etc/systemd/system/
    volumes:
      - /srv/lldap:/data
    env:
      LLDAP_JWT_SECRET: "{{ lldap_jwt_secret }}"
      LLDAP_LDAP_USER_PASS: "{{ lldap_admin_password }}"
      LLDAP_LDAP_BASE_DN: "{{ lldap_base_dn }}"
    timezone: "{{ podman_timezone }}"
  notify: "restart lldap service"
