---
- name: create dirs
  file:
    state: directory
    path: "/srv/pihole/{{ item }}"
  loop:
    - config
    - dnsmasq.d
- name: create pihole container
  containers.podman.podman_container:
    name: pihole
    state: created
    image: docker.io/pihole/pihole
    generate_systemd:
      path: /etc/systemd/system/
    volumes:
      - /srv/pihole/config/:/etc/pihole/
      - /srv/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    publish:
      - "{{ ansible_host }}:53:53/udp"
      - "67:67/udp"
      - "8012:80/tcp"
      - "12443:443/tcp"
    env:
      WEBPASSWORD: "{{ pihole_password }}"
    timezone: "{{ podman_timezone }}"
  notify: "restart pihole service"
